// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfIWcu55sDymrf-jI6k49ezdRpPIO8vZs',
    appId: '1:892439469312:web:ec609a7d56f5b71011e7e5',
    messagingSenderId: '892439469312',
    projectId: 'baithick',
    authDomain: 'baithick.firebaseapp.com',
    databaseURL: 'https://baithick-default-rtdb.firebaseio.com',
    storageBucket: 'baithick.firebasestorage.app',
    measurementId: 'G-J5R1Z81NWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLLZscSBliJJDU3r9CJWxfFCI3QJRdwwo',
    appId: '1:892439469312:android:f4573c4c904b0dfa11e7e5',
    messagingSenderId: '892439469312',
    projectId: 'baithick',
    databaseURL: 'https://baithick-default-rtdb.firebaseio.com',
    storageBucket: 'baithick.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgpx2CD_0DaDNof_Ue0HLnKa4r38aQiXo',
    appId: '1:892439469312:ios:7bfec12106c160a611e7e5',
    messagingSenderId: '892439469312',
    projectId: 'baithick',
    databaseURL: 'https://baithick-default-rtdb.firebaseio.com',
    storageBucket: 'baithick.firebasestorage.app',
    iosClientId: '892439469312-hrdb68p3h3oush7uadksgsho953hn7ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.baithick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgpx2CD_0DaDNof_Ue0HLnKa4r38aQiXo',
    appId: '1:892439469312:ios:7bfec12106c160a611e7e5',
    messagingSenderId: '892439469312',
    projectId: 'baithick',
    databaseURL: 'https://baithick-default-rtdb.firebaseio.com',
    storageBucket: 'baithick.firebasestorage.app',
    iosClientId: '892439469312-hrdb68p3h3oush7uadksgsho953hn7ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.baithick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfIWcu55sDymrf-jI6k49ezdRpPIO8vZs',
    appId: '1:892439469312:web:d282a7d23c26318311e7e5',
    messagingSenderId: '892439469312',
    projectId: 'baithick',
    authDomain: 'baithick.firebaseapp.com',
    databaseURL: 'https://baithick-default-rtdb.firebaseio.com',
    storageBucket: 'baithick.firebasestorage.app',
    measurementId: 'G-3JGNQRGF0M',
  );

}