// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxSM691Z9cQ2RXBPO0zimXQ4okBslUE0Q',
    appId: '1:579685954133:web:032a63a8cd17845c5a9adc',
    messagingSenderId: '579685954133',
    projectId: 'noteapp-5ea9b',
    authDomain: 'noteapp-5ea9b.firebaseapp.com',
    storageBucket: 'noteapp-5ea9b.firebasestorage.app',
    measurementId: 'G-6NRTSJV736',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Gr6pMVutC7mVo4V9hMERLIYqlgNvK5Q',
    appId: '1:579685954133:android:f9b80bca8dd3ab435a9adc',
    messagingSenderId: '579685954133',
    projectId: 'noteapp-5ea9b',
    storageBucket: 'noteapp-5ea9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA9gCyXHSTBMglHj_pAtV2n9t-SefPvHo',
    appId: '1:579685954133:ios:020d5558766f67225a9adc',
    messagingSenderId: '579685954133',
    projectId: 'noteapp-5ea9b',
    storageBucket: 'noteapp-5ea9b.firebasestorage.app',
    iosClientId: '579685954133-c65dvqb64990dbo9f8jjv6bvqua6lpqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.baithick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA9gCyXHSTBMglHj_pAtV2n9t-SefPvHo',
    appId: '1:579685954133:ios:020d5558766f67225a9adc',
    messagingSenderId: '579685954133',
    projectId: 'noteapp-5ea9b',
    storageBucket: 'noteapp-5ea9b.firebasestorage.app',
    iosClientId: '579685954133-c65dvqb64990dbo9f8jjv6bvqua6lpqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.baithick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxSM691Z9cQ2RXBPO0zimXQ4okBslUE0Q',
    appId: '1:579685954133:web:b47be6efe0517ba85a9adc',
    messagingSenderId: '579685954133',
    projectId: 'noteapp-5ea9b',
    authDomain: 'noteapp-5ea9b.firebaseapp.com',
    storageBucket: 'noteapp-5ea9b.firebasestorage.app',
    measurementId: 'G-6XG2G17X9N',
  );

}